"""add follow table

Revision ID: 417fdcfb6e39
Revises: 72dd9b6855e7
Create Date: 2023-10-30 14:16:39.885217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417fdcfb6e39'
down_revision = '72dd9b6855e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
